### ISSUE TITLE
test.config file missing

### ISSUE THREAD

**Issue by wchen190** [CDCgov/bpertussis-ciwgs#2]
After installation, running the following command generated error:
nextflow run Bpertussis-CIWGS/main.nf -profile test,docker

ERROR ~ No such file or directory: Config file does not exist: bpertussis-ciwgs/conf/test.config

**Comment by mikeyweigand** [comment]
Corrected error in greedy `.gitignore` match. Test config has been added and test samplesheet updated with included read subsamples.
